import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { runtimeDataReady, runtimeDataset, runtimeDataRevision } from '../../persistence/runtime-data.js';
import { loadQuranCorpus, normalizedArabic, type QuranAyah } from '../quran-corpus.js';
import type { GrammarFrame, GrammarFrameKind, GrammarToken, QuranGrammarAnalysis } from './types.js';
type Loose=Record<string,any>;
let profileCache:Loose|null=null; let profileRevision=-1; let profileRoot=''; let snapshotCache:{key:string;value:any}|null=null;
function loadProfile(root=process.cwd()):Loose{const rev=runtimeDataRevision(),rr=path.resolve(root);if(profileCache&&profileRevision===rev&&profileRoot===rr)return profileCache;profileCache=null;profileRevision=rev;profileRoot=rr;if(runtimeDataReady()){try{profileCache=runtimeDataset('data/revelation/grammar-profile.json') as Loose;}catch{profileCache=null;}}if(!profileCache)profileCache=JSON.parse(fs.readFileSync(path.resolve(root,'data/revelation/grammar-profile.json'),'utf8'));return profileCache!;}
const uniq=<T>(xs:T[])=>[...new Set(xs)];
function id(kind:string,reference:string|null,index:number,surface:string){return `GRAM-${crypto.createHash('sha256').update(`${kind}|${reference??'SURFACE'}|${index}|${surface}`).digest('hex').slice(0,16)}`;}
function peelLeadingClitics(token:string,p:Loose){const allowed=new Set<string>(p?.morphology?.leadingClitics??[]);const clitics:string[]=[];let rest=token;for(let i=0;i<2&&rest.length>3;i++){const first=rest[0];if(!allowed.has(first))break;clitics.push(first);rest=rest.slice(1);}return{clitics,rest};}
function stemCandidateOf(token:string,p:Loose){const {clitics,rest:initial}=peelLeadingClitics(token,p);let stem=initial;const article=String(p?.morphology?.definiteArticle??'ال');if(stem.startsWith(article)&&stem.length>4)stem=stem.slice(article.length);const suffixes=[...(p?.morphology?.pluralSuffixes??[]),...(p?.morphology?.pronounSuffixes??[])].sort((a:string,b:string)=>b.length-a.length);for(const suffix of suffixes){if(stem.endsWith(suffix)&&stem.length-suffix.length>=3){stem=stem.slice(0,-suffix.length);break;}}const letters=stem.replace(/[^\p{L}]/gu,'');const root=letters.length===3?letters:null;return{clitics,stem,root,confidence:root?0.55:0.38};}
function tokenize(text:string,p:Loose):GrammarToken[]{return normalizedArabic(text).split(/\s+/).filter(Boolean).map((surface,index)=>{const m=stemCandidateOf(surface,p);return{index,surface,normalized:surface,leadingClitics:m.clitics,stemCandidate:m.stem,rootCandidate:m.root,canonicalRoot:null,morphologyConfidence:m.confidence};});}
function bare(token:string,p:Loose){return peelLeadingClitics(token,p).rest;}
function divineSurface(token:string,p:Loose){return (p?.markers?.divineSubjectSurfaces??['الله']).includes(bare(token,p));}
function pluralVerbLike(token:string){const x=token.replace(/^[وف]/,'');return x.length>=4&&x.endsWith('وا');}
function finiteVerbCandidate(token:string){const x=token.replace(/^[وف]/,'');return x.length>=3 && (x.length===3 || /^[يتان]/.test(x) || /(?:تم|وا)$/.test(x) || x.startsWith('جاء') || x.startsWith('كان'));}
function clip(tokens:GrammarToken[],start:number,max=7){const s=tokens.slice(start,Math.min(tokens.length,start+max)).map(x=>x.surface).join(' ').trim();return s||null;}
function mk(kind:GrammarFrameKind,reference:string|null,index:number,surface:string,patch:Partial<GrammarFrame>):GrammarFrame{return{frameId:id(kind,reference,index,surface),kind,reference,index,subjectSurface:null,predicateSurface:null,targetSurface:null,polarity:'UNKNOWN',inheritedSubject:false,heuristic:false,confidence:0.7,evidenceSurface:surface,...patch};}
export function analyzeArabicRevelationSurface(text:string,options:{reference?:string|null;root?:string}={}):QuranGrammarAnalysis{const root=options.root??process.cwd(),p=loadProfile(root),reference=options.reference??null,tokens=tokenize(text,p),frames:GrammarFrame[]=[];const neg=new Set<string>(p?.markers?.negation??[]),predicateFamilies=(p?.markers?.divinePredicateFamilies??[]) as string[],conditions=new Set<string>(p?.markers?.condition??[]),vocatives=new Set<string>(p?.markers?.vocative??[]),speech=new Set<string>(p?.markers?.speech??[]),causes=new Set<string>(p?.markers?.causeCandidate??[]),purposes=new Set<string>(p?.markers?.purposeResultCandidate??[]),exclusions=new Set<string>((p?.markers?.imperativeExclusions??[]).map((x:string)=>normalizedArabic(x))),avoidance=String(p?.markers?.avoidanceStem??'اجتنب');let lastDivine=-999;
for(let i=0;i<tokens.length;i++){const t=tokens[i].surface,b=bare(t,p),next=tokens[i+1]?.surface??'',next2=tokens[i+2]?.surface??'';if(divineSurface(t,p)){lastDivine=i;let predicate=next,targetStart=i+2,polarity:'POSITIVE'|'NEGATIVE'|'NEUTRAL'|'UNKNOWN'='NEUTRAL',evidence=`${t} ${next}`.trim(),confidence=.92;if(neg.has(next)){predicate=next2;targetStart=i+3;polarity='NEGATIVE';evidence=`${t} ${next} ${next2}`.trim();confidence=.96;}if(predicate)frames.push(mk('DIVINE_PREDICATE',reference,i,evidence,{subjectSurface:t,predicateSurface:predicate,targetSurface:clip(tokens,targetStart,6),polarity,confidence}));}
if(i-lastDivine<=12 && /^[وف]/.test(t) && predicateFamilies.some((x:string)=>b.startsWith(x))){const coordinatedPolarity=b.startsWith('ينهى')?'NEGATIVE':'NEUTRAL';frames.push(mk('COORDINATED_PREDICATE',reference,i,t,{subjectSurface:'الله',predicateSurface:t,targetSurface:clip(tokens,i+1,7),polarity:coordinatedPolarity,inheritedSubject:true,confidence:b.startsWith('ينهى')?.88:.78}));}
if(['لا','ولا','فلا'].includes(t)&&pluralVerbLike(next))frames.push(mk('PROHIBITION',reference,i,`${t} ${next}`,{predicateSurface:next,targetSurface:clip(tokens,i+2,5),polarity:'NEGATIVE',confidence:.9}));const av=b.replace(/^[وف]/,'');if(av.startsWith(avoidance)&&pluralVerbLike(av))frames.push(mk('PROHIBITION',reference,i,t,{predicateSurface:t,targetSurface:clip(tokens,i+1,6),polarity:'NEGATIVE',confidence:.94}));
if(pluralVerbLike(t)&&!exclusions.has(t)&&!['لا','ولا','فلا'].includes(tokens[i-1]?.surface??'')){const raw=t.replace(/^[وف]/,'');if(raw&&!exclusions.has(raw)&&!raw.startsWith(avoidance))frames.push(mk('IMPERATIVE_CANDIDATE',reference,i,t,{predicateSurface:t,targetSurface:clip(tokens,i+1,5),polarity:'POSITIVE',heuristic:true,confidence:.42}));}
if((t==='اذا'||t==='لو'||[...conditions].some(x=>['اذا','لو'].includes(x)&&t.startsWith(x)&&t.length>x.length+1)))frames.push(mk('CONDITION_EXPLICIT',reference,i,t,{predicateSurface:t,targetSurface:clip(tokens,i+1,7),polarity:'NEUTRAL',heuristic:false,confidence:.88}));if((t==='من'&&finiteVerbCandidate(next)) || (t==='ان'&&finiteVerbCandidate(next)))frames.push(mk('CONDITION_CANDIDATE',reference,i,t,{predicateSurface:t,targetSurface:clip(tokens,i+1,7),polarity:'NEUTRAL',heuristic:true,confidence:.62}));if(vocatives.has(t))frames.push(mk('VOCATIVE',reference,i,t,{predicateSurface:t,targetSurface:clip(tokens,i+1,6),polarity:'NEUTRAL',confidence:.9}));if(speech.has(t))frames.push(mk('SPEECH',reference,i,t,{predicateSurface:t,targetSurface:clip(tokens,i+1,7),polarity:'NEUTRAL',confidence:.84}));if(causes.has(t)||[...causes].some(x=>t.startsWith(x)&&t.length>x.length+1))frames.push(mk('CAUSE_CANDIDATE',reference,i,t,{predicateSurface:t,targetSurface:clip(tokens,i+1,6),polarity:'NEUTRAL',heuristic:true,confidence:.48}));if(purposes.has(t)||[...purposes].some(x=>t.startsWith(x)&&t.length>x.length+1))frames.push(mk('PURPOSE_RESULT_CANDIDATE',reference,i,t,{predicateSurface:t,targetSurface:clip(tokens,i+1,6),polarity:'NEUTRAL',heuristic:true,confidence:.45}));}
const dedup=[...new Map(frames.map(x=>[x.frameId,x] as const)).values()];return{protocol:'REVELATION_GRAMMAR_ANALYSIS_V1',version:'4.29.0',reference,text,tokens,frames:dedup,speakerSurfaces:uniq(dedup.filter(x=>x.kind==='SPEECH').map(x=>x.evidenceSurface)),addresseeSurfaces:uniq(dedup.filter(x=>x.kind==='VOCATIVE').map(x=>x.targetSurface).filter(Boolean) as string[]),invariants:{normativeAuthority:false,externalLexiconUsed:false,canonicalRootClaimed:false,placeOfRevelationInferred:false},boundary:'Structural grammar analysis only. Root values are low-confidence surface-derived candidates; canonical Arabic roots/lemmas are not asserted without corpus-internal proof.'};}
export function analyzeQuranAyahGrammar(ayah:QuranAyah,root=process.cwd()){return analyzeArabicRevelationSurface(ayah.text,{reference:`Q${ayah.reference}`,root});}
export function revelationGrammarSnapshot(root=process.cwd(),options:{sampleLimit?:number}={}){const key=`${path.resolve(root)}|${runtimeDataRevision()}|${options.sampleLimit??40}`;if(snapshotCache?.key===key)return snapshotCache.value;const counts:Record<string,number>={},samples:GrammarFrame[]=[];let tokenCount=0,ayahsWithFrames=0;const corpus=loadQuranCorpus(root);for(const ayah of corpus){const a=analyzeQuranAyahGrammar(ayah,root);tokenCount+=a.tokens.length;if(a.frames.length)ayahsWithFrames++;for(const f of a.frames){counts[f.kind]=(counts[f.kind]??0)+1;if(samples.length<(options.sampleLimit??40))samples.push(f);}}const value={protocol:'REVELATION_GRAMMAR_ENGINE_V1',version:'4.29.0',scope:'QURAN_PRIMARY_GRAMMAR_ONLY',ayahCount:corpus.length,tokenCount,ayahsWithFrames,frameCount:Object.values(counts).reduce((a,b)=>a+b,0),countsByKind:counts,samples,invariants:{normativeAuthority:false,quranPrimaryMuhaimin:true,textualWitnessGrammarMayOutvoteQuran:false,externalLexiconUsed:false,canonicalRootClaimed:false,rootCandidateIsEngineeringHeuristic:true},boundary:'The grammar engine extracts structural relation frames from Quran text. Tawrat/Zabur/Injil remain corroborative textual witnesses and do not override Quran grammar or moral direction.'};snapshotCache={key,value};return value;}
export function resetRevelationGrammarCacheForTests(){profileCache=null;profileRevision=-1;profileRoot='';snapshotCache=null;}
