import { useCallback, useEffect, useState } from 'react';
import { api } from '../lib/api';
import { Button } from './ui/Button';
import { Input } from './ui/Input';

const nextActions:Record<string,string[]>={QUEUED:['ASSIGNED','ACKNOWLEDGED','ESCALATED'],ASSIGNED:['ACKNOWLEDGED','EVIDENCE_REQUESTED','ESCALATED'],ACKNOWLEDGED:['EVIDENCE_REQUESTED','DISPOSED','ESCALATED'],EVIDENCE_REQUESTED:['ACKNOWLEDGED','DISPOSED','ESCALATED'],DISPOSED:['REOPENED'],ESCALATED:['ACKNOWLEDGED','DISPOSED','REOPENED'],REOPENED:['ASSIGNED','ACKNOWLEDGED','EVIDENCE_REQUESTED','ESCALATED']};

export function ReviewQueue(){
  const [reviews,setReviews]=useState<any[]>([]);const [targetId,setTargetId]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const load=useCallback(async()=>{try{const data=await api.reviews();setReviews((data.reviews??[]).map((item:any)=>item.payload??item));}catch(err){setError(err instanceof Error?err.message:'REVIEW_QUEUE_ERROR');}},[]);
  useEffect(()=>{load();},[load]);
  const create=async()=>{if(!targetId.trim())return;setBusy(true);setError('');try{await api.createReview({targetId:targetId.trim(),gateDecision:'REQUIRE_HUMAN_REVIEW',evidenceRefs:[]});setTargetId('');await load();}catch(err){setError(err instanceof Error?err.message:'REVIEW_CREATE_ERROR');}finally{setBusy(false);}};
  const transition=async(review:any,status:string)=>{const disposition=status==='DISPOSED'?'UPHOLD_GATE':undefined;const rationale=status==='DISPOSED'?window.prompt('Reviewer rationale (required for audit):')??'':'';if(status==='DISPOSED'&&!rationale)return;setBusy(true);setError('');try{await api.transitionReview(review.reviewId,{status,disposition,rationale});await load();}catch(err){setError(err instanceof Error?err.message:'REVIEW_TRANSITION_ERROR');}finally{setBusy(false);}};
  return <div className="mw-stack"><div className="mw-playground-hero"><div><div className="mw-eyebrow">GOVERNED HUMAN REVIEW</div><h2>Review Queue</h2><p>Gate decision, reviewer disposition, and operational action remain separate. Original analysis and Witness commitments are never rewritten here.</p></div><div className="mw-playground-badge">{reviews.filter(r=>r.status!=='DISPOSED').length} OPEN</div></div><div className="mw-ai-card mw-review-create"><div><div className="mw-ai-card-title">CREATE REVIEW</div><p className="mw-muted">Queue an analysis or case identifier for governed review.</p></div><div className="mw-review-create-form"><Input aria-label="Review target ID" value={targetId} onChange={e=>setTargetId(e.target.value)} placeholder="CASE / EVALUATION ID"/><Button onClick={create} disabled={busy||!targetId.trim()}>Queue review</Button></div></div>{error&&<div className="mw-error" role="alert">{error}</div>}<div className="mw-review-queue">{reviews.length?reviews.map(review=><article className="mw-review-item" key={review.reviewId}><div className="mw-review-item-head"><div><span>{review.status}</span><h3>{review.targetId}</h3></div><small>v{review.version} · {review.reviewId}</small></div><div className="mw-status-grid"><div><span>Gate decision</span><strong>{review.gateDecision}</strong></div><div><span>Human disposition</span><strong>{review.disposition??'PENDING'}</strong></div><div><span>Assignee</span><strong>{review.assigneeId??'UNASSIGNED'}</strong></div><div><span>Evidence refs</span><strong>{review.evidenceRefs?.length??0}</strong></div></div>{review.rationale&&<div className="mw-boundary-note">Rationale: {review.rationale}</div>}<div className="mw-review-actions">{(nextActions[review.status]??[]).map(status=><Button key={status} variant="ghost" disabled={busy} onClick={()=>transition(review,status)}>{status.replaceAll('_',' ')}</Button>)}</div></article>):<div className="mw-empty">No review records yet.</div>}</div></div>;
}
