import { useEffect, useId, useRef, type ButtonHTMLAttributes, type HTMLAttributes, type InputHTMLAttributes, type PropsWithChildren, type ReactNode } from 'react';

export type ButtonVariant = 'default' | 'ghost' | 'danger' | 'primary' | 'secondary';
export type BadgeTone = 'default' | 'success' | 'warning' | 'danger' | 'info' | string;
export function Button({className='',variant='default',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:ButtonVariant}){return <button className={`mw-button mw-button-${variant} ${className}`} {...props}/>;}
export function Input({className='',...props}:InputHTMLAttributes<HTMLInputElement>){return <input className={`mw-input ${className}`} {...props}/>;}
export function Badge({className='',tone='default',...props}:PropsWithChildren<HTMLAttributes<HTMLSpanElement>&{tone?:BadgeTone}>){return <span className={`mw-badge mw-badge-${tone} ${className}`} {...props}/>;}
export function Card({className='',...props}:HTMLAttributes<HTMLDivElement>){return <div className={`mw-card ${className}`} {...props}/>;}
export function CardHeader({className='',...props}:HTMLAttributes<HTMLDivElement>){return <div className={`mw-card-header ${className}`} {...props}/>;}
export function CardTitle({className='',...props}:HTMLAttributes<HTMLHeadingElement>){return <h3 className={`mw-card-title ${className}`} {...props}/>;}
export function CardContent({className='',...props}:HTMLAttributes<HTMLDivElement>){return <div className={`mw-card-content ${className}`} {...props}/>;}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const titleId=useId();const dialogRef=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();};document.addEventListener('keydown',onKey);dialogRef.current?.querySelector<HTMLButtonElement>('.mw-modal-close')?.focus();return()=>{document.removeEventListener('keydown',onKey);previous?.focus();};},[onClose]);return <div className="mw-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><div ref={dialogRef} className="mw-modal-content" role="dialog" aria-modal="true" aria-labelledby={titleId}><Card className="mw-modal-card"><CardHeader className="mw-modal-header" style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><CardTitle id={titleId}>{title}</CardTitle><Button type="button" variant="ghost" onClick={onClose} aria-label="Close dialog" className="mw-modal-close" style={{padding:'.25rem .5rem'}}>✕</Button></CardHeader><CardContent>{children}</CardContent></Card></div></div>;}
