import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { BoundaryNotice, Button, CivicShell, Input, Modal, ReviewGatePanel, StatusBadge, Surface, WitnessPanel, useCivicPreferences, type CivicLocale } from '@moonwitness/ui';

const API_BASE=import.meta.env.VITE_API_URL??'http://127.0.0.1:8787';
type User={userId:string;rid:string|null;roles:string[]};
type Flow={id:string;name:string;status:string;version:number;nodes:Array<{id:string;kind:string;label:string}>;reviewGate?:{decision?:string;requiresHumanReview?:boolean;adverseActionBlocked?:boolean};witness?:{state?:string;hash?:string|null;root?:string|null;checkpointId?:string|null};updatedAt?:string};
function mutationKey():string{return globalThis.crypto?.randomUUID?.()??`flow-${Date.now()}-${Math.random().toString(36).slice(2)}`;}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const method=String(init?.method??'GET').toUpperCase();const headers=new Headers(init?.headers);if(init?.body)headers.set('content-type','application/json');if(!['GET','HEAD'].includes(method)&&!path.startsWith('/api/v1/auth/'))headers.set('idempotency-key',mutationKey());const response=await fetch(`${API_BASE}${path}`,{...init,credentials:'include',headers});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.message??body?.error??`HTTP ${response.status}`);return body as T;}
const copy={id:{app:'Flow Studio',eyebrow:'ALUR TERKELOLA · RID TERBATAS',studio:'Studio',runs:'Riwayat Eksekusi',contracts:'Kontrak',versions:'Versi',access:'Akses',title:'Alur Penanganan Bukti',draft:'DRAF TERKELOLA',notice:'HUMAN AUTHORITY · LIMITED',scope:'Alur hanya dapat dijalankan dalam peran, tujuan, dan lingkup RID yang eksplisit.',session:'Masuk dengan akun XRP untuk membuka sesi Flow.',validate:'Validasi struktur',publish:'Ajukan tinjauan',trigger:'Pemicu',verify:'Verifikasi bukti',gate:'Gerbang manusia',commit:'Witness commit',approval:'Publikasi atau tindakan berdampak memerlukan persetujuan manusia.',create:'Buat alur',name:'Nama alur',save:'Simpan alur',refresh:'Muat ulang',signin:'Masuk ke Flow',username:'Nama pengguna',password:'Kata sandi',submit:'Masuk aman',empty:'Belum ada alur untuk RID ini.'},en:{app:'Flow Studio',eyebrow:'GOVERNED AUTOMATION · RID SCOPED',studio:'Studio',runs:'Execution History',contracts:'Contracts',versions:'Versions',access:'Access',title:'Evidence Handling Flow',draft:'GOVERNED DRAFT',notice:'HUMAN AUTHORITY · LIMITED',scope:'A flow may only execute within explicit role, purpose, and RID scope.',session:'Sign in with your XRP account to open a Flow session.',validate:'Validate structure',publish:'Request review',trigger:'Trigger',verify:'Verify evidence',gate:'Human gate',commit:'Witness commit',approval:'Publication or impactful action requires human approval.',create:'Create flow',name:'Flow name',save:'Save flow',refresh:'Refresh',signin:'Sign in to Flow',username:'Username',password:'Password',submit:'Secure sign in',empty:'No workflows exist for this RID yet.'}};

export default function App(){
  const prefs=useCivicPreferences('id');const t=copy[prefs.locale];const [active,setActive]=useState('studio');const [user,setUser]=useState<User|null>(null);const [flows,setFlows]=useState<Flow[]>([]);const [selectedId,setSelectedId]=useState<string|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [creating,setCreating]=useState(false);const [username,setUsername]=useState('');const [password,setPassword]=useState('');
  const nav=useMemo(()=>[{id:'studio',label:t.studio},{id:'runs',label:t.runs},{id:'contracts',label:t.contracts},{id:'versions',label:t.versions},{id:'access',label:t.access}], [t]); const selected=flows.find(flow=>flow.id===selectedId)??flows[0]??null;
  async function load(){setError('');try{const result=await api<{workflows:Flow[]}>('/api/v1/flow/workflows');setFlows(result.workflows);setSelectedId(current=>result.workflows.some(item=>item.id===current)?current:result.workflows[0]?.id??null);}catch(reason){setFlows([]);setError(reason instanceof Error?reason.message:String(reason));}}
  useEffect(()=>{api<User>('/api/v1/auth/me').then(next=>{setUser(next);void load();}).catch(()=>setUser(null));},[]);
  async function login(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const result=await api<{user:User}>('/api/v1/auth/login',{method:'POST',body:JSON.stringify({username,password})});setUser(result.user);setPassword('');await load();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const name=String(new FormData(event.currentTarget).get('name')??'');setBusy(true);setError('');try{await api('/api/v1/flow/workflows',{method:'POST',body:JSON.stringify({name})});setCreating(false);await load();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}}
  async function requestReview(){if(!selected)return;setBusy(true);setError('');try{await api(`/api/v1/flow/workflows/${encodeURIComponent(selected.id)}/request-review`,{method:'POST'});await load();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}}
  return <CivicShell appCode="FLOW" appName={t.app} eyebrow={t.eyebrow} nav={nav} active={active} onNavigate={setActive} identity={user?.rid?{rid:user.rid,role:user.roles[0]??'USER',clearance:'FLOW SCOPE'}:undefined} theme={prefs.theme} locale={prefs.locale} onThemeChange={prefs.setTheme} onLocaleChange={(v:CivicLocale)=>prefs.setLocale(v)} actions={user?<><Button variant="ghost" onClick={()=>void load()}>{t.refresh}</Button><Button onClick={()=>setCreating(true)}>{t.create}</Button></>:undefined}><div className="flow-stack">
    <BoundaryNotice>{t.notice} · {t.scope}</BoundaryNotice>{error&&<BoundaryNotice tone="danger">{error}</BoundaryNotice>}
    {!user?<Surface eyebrow="RID ACCESS" title={t.signin}><form className="flow-login" onSubmit={login}><p>{t.session}</p><label>{t.username}<Input autoComplete="username" value={username} onChange={event=>setUsername(event.target.value)} required/></label><label>{t.password}<Input type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} required minLength={12}/></label><Button disabled={busy}>{busy?'…':t.submit}</Button></form></Surface>:<>
    <Surface eyebrow="FLOW WORKSPACE" title={selected?.name??t.title} actions={<div className="flow-actions"><StatusBadge tone={selected?.status==='REVIEW_REQUIRED'?'warning':'provisional'}>{selected?.status??t.draft}</StatusBadge><Button variant="ghost" onClick={()=>void load()}>{t.validate}</Button><Button disabled={!selected||busy||selected.status==='REVIEW_REQUIRED'} onClick={()=>void requestReview()}>{t.publish}</Button></div>}><div className="flow-canvas" aria-label="Governed workflow editor"><div className="flow-grid"/>{(selected?.nodes??[]).map((node,index)=><FlowNode key={node.id} x={[5,28,52,76][index]??5} y={[42,20,48,23][index]??42} kind={node.kind} title={node.label} detail={node.kind==='HUMAN_REVIEW'?t.approval:node.kind==='WITNESS'?'Hash-only commitment':'Governed flow node'} tone={node.kind==='HUMAN_REVIEW'?'warning':node.kind==='WITNESS'?'info':node.kind==='POLICY'?'positive':'neutral'}/>)}{selected&&<svg className="flow-links" viewBox="0 0 1000 430" preserveAspectRatio="none" aria-hidden="true"><path d="M145 235 C220 235 210 125 300 125"/><path d="M425 125 C500 125 485 255 555 255"/><path d="M680 255 C745 255 730 135 795 135"/></svg>}{!selected&&<div className="flow-empty">{t.empty}</div>}</div></Surface>
    <div className="flow-governed"><ReviewGatePanel title={t.gate} gate={selected?.reviewGate?{...selected.reviewGate,severity:'HIGH',reasons:[t.approval],boundary:`${t.notice} · ${t.scope}`}:{decision:'REVIEW_REQUIRED',severity:'HIGH',requiresHumanReview:true,adverseActionBlocked:true,reasons:[t.approval],boundary:`${t.notice} · ${t.scope}`}}/><WitnessPanel title={t.commit} witness={selected?.witness??{state:'PENDING'}}/></div>
    <div className="flow-legend"><span><i className="event"/>EVENT</span><span><i className="policy"/>POLICY CHECK</span><span><i className="review"/>HUMAN REVIEW</span><span><i className="witness"/>WITNESS</span></div></>}
  </div>{creating&&<Modal title={t.create} onClose={()=>setCreating(false)}><form className="flow-login" onSubmit={create}><label>{t.name}<Input name="name" required maxLength={120} autoFocus/></label><BoundaryNotice>{t.approval}</BoundaryNotice><Button disabled={busy}>{busy?'…':t.save}</Button></form></Modal>}</CivicShell>;
}

function FlowNode({x,y,kind,title,detail,tone='neutral'}:{x:number;y:number;kind:string;title:string;detail:string;tone?:string}){return <article className={`flow-node flow-node-${tone}`} style={{left:`${x}%`,top:`${y}%`}} tabIndex={0}><small>{kind}</small><strong>{title}</strong><span>{detail}</span><b aria-hidden="true">⋮⋮</b></article>}
