import { useEffect, useMemo, useState, type FormEvent } from 'react';
import type { XrpWorkspaceResponse } from '@moonwitness/contracts';
import { BoundaryNotice, Button, CausalLane, CivicShell, EvidenceLedger, Input, Metric, Modal, ReviewGatePanel, StatusBadge, Surface, WitnessPanel, useCivicPreferences, type CivicLocale } from '@moonwitness/ui';

const API_BASE=import.meta.env.VITE_API_URL??'http://127.0.0.1:8787';
type User={userId:string;username:string;rid:string|null;roles:string[]};
function mutationKey():string{return globalThis.crypto?.randomUUID?.()??`xrp-${Date.now()}-${Math.random().toString(36).slice(2)}`;}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const method=String(init?.method??'GET').toUpperCase();const headers=new Headers(init?.headers);if(init?.body)headers.set('content-type','application/json');if(!['GET','HEAD'].includes(method)&&!path.startsWith('/api/v1/auth/'))headers.set('idempotency-key',mutationKey());const response=await fetch(`${API_BASE}${path}`,{...init,credentials:'include',headers});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.message??body?.error??`HTTP ${response.status}`);return body as T;}

const copy={
  id:{app:'Ruang Publik XRP',eyebrow:'RUANG KERJA SIPIL · RID TERBATAS',overview:'Ringkasan',cases:'Kasus Saya',evidence:'Bukti',projects:'Proyek',tasks:'Tugas',resources:'Sumber Daya',flow:'Flow Studio',welcome:'Ruang kendali personal Anda',intro:'Satu ruang aman untuk perkara, bukti, proyek, tugas, dan alur kerja yang berada dalam lingkup RID Anda.',active:'Kasus aktif',review:'Menunggu tinjauan',evidenceCount:'Bukti terverifikasi',tasksDue:'Tugas mendekati batas',journey:'Jalur perkara terkini',signin:'Masuk ke XRP',signinHelp:'Gunakan akun publik yang terhubung ke RID. Kredensial tidak disimpan oleh browser.',username:'Nama pengguna',password:'Kata sandi',submit:'Masuk aman',logout:'Keluar',required:'Sesi aman diperlukan',scope:'Hanya data dalam lingkup RID dan kewenangan Anda yang dapat ditampilkan.',noCase:'BELUM ADA KASUS DIPILIH',noCases:'Belum ada perkara dalam lingkup RID ini.',selectCase:'Pilih perkara',workItems:'Tugas, proyek, dan sumber daya RID',loading:'Memuat ruang kerja terverifikasi',refresh:'Muat ulang'},
  en:{app:'XRP Public Workspace',eyebrow:'CIVIC WORKSPACE · RID SCOPED',overview:'Overview',cases:'My Cases',evidence:'Evidence',projects:'Projects',tasks:'Tasks',resources:'Resources',flow:'Flow Studio',welcome:'Your personal civic command space',intro:'One secure workspace for cases, evidence, projects, tasks, and workflows within your RID scope.',active:'Active cases',review:'Awaiting review',evidenceCount:'Verified evidence',tasksDue:'Tasks approaching due',journey:'Current case journey',signin:'Sign in to XRP',signinHelp:'Use the public account connected to your RID. Credentials are never stored by the browser.',username:'Username',password:'Password',submit:'Secure sign in',logout:'Sign out',required:'Secure session required',scope:'Only data within your RID scope and explicit authority can be displayed.',noCase:'NO CASE SELECTED',noCases:'No cases are currently recorded within this RID scope.',selectCase:'Select case',workItems:'RID tasks, projects, and resources',loading:'Loading verified workspace',refresh:'Refresh'}
};

export default function App(){
  const prefs=useCivicPreferences('id');const t=copy[prefs.locale];const [active,setActive]=useState('overview');const [user,setUser]=useState<User|null>(null);const [workspace,setWorkspace]=useState<XrpWorkspaceResponse|null>(null);const [selectedId,setSelectedId]=useState<string|null>(null);const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [composer,setComposer]=useState<'case'|'evidence'|'work'|null>(null);
  const nav=useMemo(()=>[{id:'overview',label:t.overview},{id:'cases',label:t.cases},{id:'evidence',label:t.evidence},{id:'projects',label:t.projects},{id:'tasks',label:t.tasks},{id:'resources',label:t.resources},{id:'flow',label:t.flow}], [t]);
  const selected=workspace?.cases.find(item=>item.id===selectedId)??workspace?.cases[0]??null;
  async function loadWorkspace(){setLoading(true);setError('');try{const next=await api<XrpWorkspaceResponse>('/api/v1/xrp/workspace');setWorkspace(next);setSelectedId(current=>next.cases.some(item=>item.id===current)?current:next.cases[0]?.id??null);}catch(reason){setWorkspace(null);setError(reason instanceof Error?reason.message:String(reason));}finally{setLoading(false);}}
  useEffect(()=>{api<User>('/api/v1/auth/me').then(next=>{setUser(next);void loadWorkspace();}).catch(()=>setUser(null));},[]);
  async function login(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const session=await api<{user:User}>('/api/v1/auth/login',{method:'POST',body:JSON.stringify({username,password})});setUser(session.user);setPassword('');await loadWorkspace();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}}
  async function logout(){await api('/api/v1/auth/logout',{method:'POST'}).catch(()=>null);setUser(null);setWorkspace(null);setSelectedId(null);}
  async function submitComposer(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError('');try{if(composer==='case')await api('/api/v1/xrp/cases',{method:'POST',body:JSON.stringify({title:form.get('title'),description:form.get('description')})});if(composer==='evidence'&&selected)await api(`/api/v1/xrp/cases/${encodeURIComponent(selected.id)}/evidence`,{method:'POST',body:JSON.stringify({sourceType:form.get('sourceType'),reference:form.get('reference'),note:form.get('note')})});if(composer==='work')await api('/api/v1/xrp/work-items',{method:'POST',body:JSON.stringify({type:form.get('type'),title:form.get('title'),dueAt:form.get('dueAt')||undefined})});setComposer(null);await loadWorkspace();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}}
  async function requestReview(){if(!selected)return;setBusy(true);setError('');try{await api(`/api/v1/xrp/cases/${encodeURIComponent(selected.id)}/request-review`,{method:'POST'});await loadWorkspace();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}}
  const summary=workspace?.summary;
  return <CivicShell appCode="XRP" appName={t.app} eyebrow={t.eyebrow} nav={nav} active={active} onNavigate={setActive} identity={user?.rid?{rid:user.rid,role:user.roles[0]??'USER',clearance:'RID SCOPE'}:undefined} theme={prefs.theme} locale={prefs.locale} onThemeChange={prefs.setTheme} onLocaleChange={(v:CivicLocale)=>prefs.setLocale(v)} actions={user?<><Button variant="ghost" onClick={()=>void loadWorkspace()} disabled={loading}>{t.refresh}</Button><Button variant="ghost" onClick={logout}>{t.logout}</Button></>:undefined}>
    {!user?<div className="xrp-auth"><Surface eyebrow="RID ACCESS" title={t.signin}><form onSubmit={login} className="xrp-login"><p>{t.signinHelp}</p><label>{t.username}<Input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>{t.password}<Input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={12}/></label>{error&&<p className="xrp-error" role="alert">{error}</p>}<Button disabled={busy}>{busy?'…':t.submit}</Button></form></Surface><BoundaryNotice tone="info">{t.required} · {t.scope}</BoundaryNotice></div>:
    <div className="xrp-stack"><BoundaryNotice tone="info">RID {user.rid??'NOT CONNECTED'} · {t.scope}</BoundaryNotice>{error&&<BoundaryNotice tone="danger">{error}</BoundaryNotice>}{loading&&<BoundaryNotice>{t.loading}…</BoundaryNotice>}<header className="xrp-hero"><div><span className="mw-eyebrow">{active.toUpperCase()} · PERSONAL CIVIC SPACE</span><h2>{t.welcome}</h2><p>{t.intro}</p></div><StatusBadge tone={workspace?'positive':'neutral'}>{workspace?'RID SCOPE VERIFIED':'NOT LOADED'}</StatusBadge></header>
      <div className="mw-metrics"><Metric label={t.active} value={summary?String(summary.activeCases):'—'} detail="RID scoped"/><Metric label={t.review} value={summary?String(summary.awaitingReview):'—'} detail="Human authority"/><Metric label={t.evidenceCount} value={summary?String(summary.verifiedEvidence):'—'} detail="Verified or corroborated"/><Metric label={t.tasksDue} value={summary?String(summary.dueTasks):'—'} detail="Next 7 days"/></div>
      <Surface eyebrow="RID CASE INDEX" title={t.selectCase} actions={<div className="xrp-actions"><StatusBadge>{workspace?.cases.length??0} CASES</StatusBadge><Button onClick={()=>setComposer('case')}>{prefs.locale==='id'?'Buat perkara':'Create case'}</Button></div>}>{workspace?.cases.length?<div className="xrp-case-index" role="list">{workspace.cases.map(item=><button type="button" role="listitem" className={selected?.id===item.id?'is-active':''} key={item.id} onClick={()=>setSelectedId(item.id)}><span><strong>{item.title}</strong><small>{item.id}</small></span><StatusBadge tone={item.status==='COMPLETED'?'positive':'info'}>{item.status}</StatusBadge></button>)}</div>:<p className="xrp-empty">{t.noCases}</p>}</Surface>
      {!selected?<BoundaryNotice>{t.noCase} · {prefs.locale==='id'?'panel tidak menebak data pengguna':'panels do not invent user data'}</BoundaryNotice>:<><Surface eyebrow="GOVERNED CASE LIFECYCLE" title={t.journey} actions={<div className="xrp-actions"><StatusBadge>{selected.reviewGate?.decision??'NOT EVALUATED'}</StatusBadge><Button variant="ghost" onClick={()=>setComposer('evidence')}>{prefs.locale==='id'?'Tambah bukti':'Add evidence'}</Button><Button variant="ghost" onClick={()=>void requestReview()} disabled={busy}>{prefs.locale==='id'?'Minta tinjauan':'Request review'}</Button></div>}><CausalLane nodes={[{id:'report',label:prefs.locale==='id'?'Laporan':'Report',detail:selected.status},{id:'evidence',label:prefs.locale==='id'?'Bukti':'Evidence',detail:`${selected.evidence.length} scoped records`},{id:'analysis',label:prefs.locale==='id'?'Analisis':'Analysis',detail:selected.reviewGate?'Evaluated':'Not evaluated'},{id:'review',label:prefs.locale==='id'?'Tinjauan manusia':'Human review',detail:selected.reviewGate?.decision??'Not evaluated'},{id:'witness',label:'Witness',detail:selected.witness.state}]}/></Surface><div className="xrp-governed-grid"><EvidenceLedger items={selected.evidence}/><ReviewGatePanel gate={selected.reviewGate}/><WitnessPanel witness={selected.witness}/></div></>}
      <Surface eyebrow="RID WORK INDEX" title={t.workItems} actions={<div className="xrp-actions"><StatusBadge>{workspace?.workItems.length??0} ITEMS</StatusBadge><Button variant="ghost" onClick={()=>setComposer('work')}>{prefs.locale==='id'?'Buat item':'Create item'}</Button></div>}>{workspace?.workItems.length?<div className="xrp-work-index">{workspace.workItems.map(item=><div key={item.id}><span><strong>{item.title}</strong><small>{item.type} · {item.id}</small></span><StatusBadge>{item.status}</StatusBadge></div>)}</div>:<p className="xrp-empty">{prefs.locale==='id'?'Belum ada item kerja dalam lingkup RID ini.':'No work items are recorded in this RID scope.'}</p>}</Surface>
    </div>}
    {composer&&<Modal title={composer==='case'?(prefs.locale==='id'?'Buat perkara':'Create case'):composer==='evidence'?(prefs.locale==='id'?'Lampirkan bukti':'Attach evidence'):(prefs.locale==='id'?'Buat item kerja':'Create work item')} onClose={()=>setComposer(null)}><form className="xrp-composer" onSubmit={submitComposer}>{composer==='case'&&<><label>{prefs.locale==='id'?'Judul perkara':'Case title'}<Input name="title" required maxLength={160}/></label><label>{prefs.locale==='id'?'Keterangan':'Description'}<textarea name="description" maxLength={10000}/></label></>}{composer==='evidence'&&<><label>{prefs.locale==='id'?'Jenis sumber':'Source type'}<Input name="sourceType" defaultValue="USER_SUBMITTED" maxLength={80}/></label><label>{prefs.locale==='id'?'Referensi':'Reference'}<Input name="reference" maxLength={240}/></label><label>{prefs.locale==='id'?'Catatan bukti':'Evidence note'}<textarea name="note" maxLength={10000}/></label><BoundaryNotice>{prefs.locale==='id'?'Bukti baru dicatat sebagai OBSERVED. Status verifikasi hanya dapat diberikan melalui tinjauan berwenang.':'New evidence is recorded as OBSERVED. Verification is only granted through authorized review.'}</BoundaryNotice></>}{composer==='work'&&<><label>{prefs.locale==='id'?'Jenis':'Type'}<select name="type" defaultValue="TASK"><option>TASK</option><option>PROJECT</option><option>RESOURCE</option></select></label><label>{prefs.locale==='id'?'Judul':'Title'}<Input name="title" required maxLength={160}/></label><label>{prefs.locale==='id'?'Tenggat (opsional)':'Due date (optional)'}<Input name="dueAt" type="datetime-local"/></label></>}<Button disabled={busy}>{busy?'…':(prefs.locale==='id'?'Simpan secara aman':'Save securely')}</Button></form></Modal>}
  </CivicShell>;
}
