import assert from 'node:assert/strict';
import { createAuthService, createFeatureRegistry, hashPassword, verifyPassword } from '../../../src/access/index.js';
const hash = hashPassword('secret');
assert.equal(verifyPassword('secret', hash), true);
assert.equal(verifyPassword('wrong', hash), false);
const auth = createAuthService({ sessionTtlMs: 10_000 });
const user = auth.createUser({ username: 'demo', password: 'secret', rid: 'RID-001', roles: ['USER'] });
assert.equal(user.rid, 'RID-001');
const login = auth.login('demo', 'secret');
assert.ok(login?.token);
assert.equal(auth.authenticate(login.token)?.rid, 'RID-001');
assert.equal(auth.logout(login.token), true);
assert.equal(auth.authenticate(login.token), null);
const features = createFeatureRegistry([{ featureId: 'cab', enabled: true, requiredRoles: ['USER'] }, { featureId: 'admin', enabled: true, requiredRoles: ['ADMIN'] }]);
assert.equal(features.isEnabled('cab', { roles: ['USER'] }), true);
assert.equal(features.isEnabled('admin', { roles: ['USER'] }), false);
assert.equal(features.isEnabled('admin', { roles: ['ADMIN'] }), true);
assert.equal(features.size(), 2);
console.log('PASS: v3.0 access/auth/feature tests');
