import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const workspaceDirectories = ['apps/api', ...fs.readdirSync(path.join(root, 'packages'), { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => `packages/${entry.name}`)];

export function parseVersion(value) {
  const match = String(value).match(/^(\d+)\.(\d+)\.(\d+)$/);
  if (!match) throw new Error(`INVALID_SEMVER:${value}`);
  return { major: Number(match[1]), minor: Number(match[2]), patch: Number(match[3]) };
}

export function nextVersion(current, bump) {
  const version = parseVersion(current);
  if (bump === 'major') return `${version.major + 1}.0.0`;
  if (bump === 'minor') return `${version.major}.${version.minor + 1}.0`;
  if (bump === 'patch') return `${version.major}.${version.minor}.${version.patch + 1}`;
  throw new Error(`INVALID_RELEASE_BUMP:${bump}`);
}

export function classifyBump(subjects) {
  const messages = subjects.map((subject) => String(subject));
  if (messages.some((subject) => /BREAKING CHANGE|^[a-z]+(?:\([^)]*\))?!:/mi.test(subject))) return 'major';
  if (messages.some((subject) => /^feat(?:\([^)]*\))?:/i.test(subject))) return 'minor';
  if (messages.some((subject) => /^(fix|perf|revert)(?:\([^)]*\))?:/i.test(subject))) return 'patch';
  return null;
}

function git(...args) {
  return execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trim();
}

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(root, relativePath), 'utf8'));
}

function writeJson(relativePath, value) {
  fs.writeFileSync(path.join(root, relativePath), `${JSON.stringify(value, null, 2)}\n`);
}

function latestTag() {
  return git('describe', '--tags', '--match', 'v[0-9]*', '--abbrev=0');
}

function subjectsSince(tag) {
  return git('log', '--format=%s%n%b%x1e', `${tag}..HEAD`)
    .split('\x1e')
    .map((message) => message.trim())
    .filter(Boolean);
}

function updateDependencies(manifest, previousVersion, version) {
  for (const field of ['dependencies', 'devDependencies', 'peerDependencies', 'optionalDependencies']) {
    const dependencies = manifest[field];
    if (!dependencies || typeof dependencies !== 'object') continue;
    for (const [name, current] of Object.entries(dependencies)) {
      if (name.startsWith('@moonwitness/') && current === previousVersion) dependencies[name] = version;
    }
  }
}

function writeReleaseDocuments(version, previousVersion, subjects) {
  const releaseLine = `${parseVersion(version).major}.${parseVersion(version).minor}.x`;
  const notable = subjects
    .map((subject) => subject.split(/\r?\n/)[0]?.trim())
    .filter((subject) => /^(feat|fix|perf|refactor)(?:\([^)]*\))?!?:/i.test(subject))
    .slice(0, 30);
  const changes = notable.length ? notable.map((subject) => `- ${subject}`).join('\n') : '- No semver-relevant conventional commits were selected.';
  fs.writeFileSync(path.join(root, `docs/RELEASE_STATUS_${version}.md`), `# Cosmic — Release Status ${version}\n\n**Release line:** ${releaseLine}  \n**Current posture:** automated certification pending\n\nThis file is generated by the versioning workflow. A tag is created only after the exact version commit passes Cosmic CI.\n`);
  fs.writeFileSync(path.join(root, `docs/RELEASE_NOTES_${version}.md`), `# Cosmic ${version} — Release Notes\n\n**Previous version:** ${previousVersion}\n\n## Included changes\n\n${changes}\n\n## Certification boundary\n\nThis release is engine/API-only. It does not claim production readiness until the exact tagged SHA has passed the mandatory certification workflow.\n`);
  fs.writeFileSync(path.join(root, `docs/TEST_REPORT_${version}.md`), `# Cosmic — Test Report ${version}\n\n**Release:** \`${version}\`  \n**Status:** automated certification pending\n\nThe release workflow creates this identity artifact. The authoritative result is the exact-SHA Cosmic CI run, including package runtime, lint, typecheck, release contracts, PostgreSQL, API build, final certification, and container build.\n`);
  for (const relativePath of ['docs/FINAL_STATUS.md', 'docs/ROADMAP_TODO.md', 'docs/PRODUCTION_CERTIFICATION.md']) {
    const absolutePath = path.join(root, relativePath);
    const text = fs.readFileSync(absolutePath, 'utf8');
    if (!text.includes(version)) fs.appendFileSync(absolutePath, `\n\n<!-- automated-release-version: ${version} -->\n`);
  }
}

export function releasePlan() {
  const current = readJson('package.json').version;
  const tag = latestTag();
  const previousVersion = tag.slice(1);
  const subjects = subjectsSince(tag);
  const bump = classifyBump(subjects);
  return { current, tag, previousVersion, bump, version: bump ? nextVersion(previousVersion, bump) : null, subjects };
}

export function applyReleaseVersion(version, previousVersion, subjects) {
  parseVersion(version);
  for (const relativePath of ['package.json', ...workspaceDirectories.map((directory) => `${directory}/package.json`)]) {
    const manifest = readJson(relativePath);
    manifest.version = version;
    updateDependencies(manifest, previousVersion, version);
    writeJson(relativePath, manifest);
  }
  const lockfile = readJson('package-lock.json');
  lockfile.version = version;
  for (const [name, entry] of Object.entries(lockfile.packages ?? {})) {
    if (name === '' || name === 'apps/api' || name.startsWith('packages/')) {
      entry.version = version;
      updateDependencies(entry, previousVersion, version);
    }
  }
  writeJson('package-lock.json', lockfile);
  writeJson('config/release-version.json', { protocol: 'COSMIC_RELEASE_VERSION_V1', version, previousVersion });
  writeReleaseDocuments(version, previousVersion, subjects);
}

function main() {
  const command = process.argv[2] ?? 'plan';
  if (command === 'plan') {
    const plan = releasePlan();
    if (process.env.GITHUB_OUTPUT) {
      try {
        fs.appendFileSync(process.env.GITHUB_OUTPUT, [
          `current=${plan.current}`,
          `version=${plan.version || ''}`,
          `tag=${plan.tag}`,
          `tag_version=${plan.previousVersion}`,
        ].join('\n') + '\n');
      } catch {
        // ignore in non-CI environment
      }
    }
    console.log(JSON.stringify(plan));
    return;
  }
  if (command === 'apply') {
    const versionIndex = process.argv.indexOf('--version');
    if (versionIndex < 0) throw new Error('RELEASE_VERSION_ARGUMENT_REQUIRED');
    const version = process.argv[versionIndex + 1];
    const plan = releasePlan();
    applyReleaseVersion(version, plan.previousVersion, plan.subjects);
    console.log(JSON.stringify({ status: 'APPLIED', version, previousVersion: plan.previousVersion }));
    return;
  }
  throw new Error(`UNKNOWN_RELEASE_VERSION_COMMAND:${command}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) main();
