export interface DomainType {
  typeId: string;
  entityFamily: string;
  domain: string;
}

const rawTypes: Array<[string, string]> = [
  ['SYSTEM.CAB', 'ENTITY'], ['SYSTEM.CHANGE_REQUEST', 'EVENT'], ['SYSTEM.VERIFICATION_CASE', 'ENTITY'],
  ['IDENTITY.ACTOR', 'ENTITY'], ['CAB.BOARD', 'ENTITY'], ['CAB.CHANGE_REQUEST', 'EVENT'], ['CAB.WORKFLOW', 'ENTITY'], ['CAB.CLARIFICATION', 'EVENT'],
  ['DIVINE_BOOK', 'ENTITY'], ['DIVINE_BOOK.SURAH', 'ENTITY'], ['DIVINE_BOOK.TAWRAT_WITNESS_PASSAGE', 'EVENT'], ['DIVINE_BOOK.ZABUR_WITNESS_PASSAGE', 'EVENT'], ['DIVINE_BOOK.INJIL_WITNESS_PASSAGE', 'EVENT'],
  ['REVELATION.DERIVED_INDEX', 'ENTITY'], ['REVELATION.PROPHET_PROFILE', 'ENTITY'], ['KNOWLEDGE.SOURCE', 'ENTITY'], ['KNOWLEDGE.EDITION', 'ENTITY'], ['KNOWLEDGE.COLLECTION', 'ENTITY'], ['KNOWLEDGE.SECTION', 'ENTITY'], ['KNOWLEDGE.PASSAGE', 'EVENT'], ['KNOWLEDGE.CLAIM', 'EVENT'], ['KNOWLEDGE.INTERPRETATION', 'EVENT'], ['KNOWLEDGE.EVIDENCE', 'EVENT'], ['KNOWLEDGE.TRANSLATION', 'EVENT'], ['KNOWLEDGE.MANUSCRIPT', 'ENTITY'], ['KNOWLEDGE.CLAIM_REVIEW', 'EVENT'], ['KNOWLEDGE.SCRIPTURE_REFERENCE', 'RELATION'], ['KNOWLEDGE.PROPHETIC_EVENT', 'EVENT'],
  ['AI.ANALYSIS', 'EVENT'], ['AI.INTENT', 'EVENT'], ['AI.ENTITY_EXTRACTION', 'EVENT'], ['ASMA.ATTRIBUTE', 'ENTITY'], ['ASMA.ESSENCE_VECTOR', 'EVENT'], ['MIZAN.EVALUATION', 'EVENT'], ['MIZAN.SCALE_PROFILE', 'ENTITY'], ['XP.SCORE', 'EVENT'],
  ['SCENARIO.SCENARIO', 'ENTITY'], ['SCENARIO.MISSION', 'ENTITY'], ['SCENARIO.SHADOW_PROFILE', 'ENTITY'], ['SHADOW.PROFILE', 'ENTITY'], ['HERO_REFERENCE.PROPHET', 'ENTITY'], ['SCENARIO.WORLD_STATE', 'ENTITY'],
  ['WORLD.COUNTRY', 'ENTITY'], ['WORLD.REGION', 'ENTITY'], ['WORLD.PLACE', 'ENTITY'], ['SPACE.OBJECT', 'ENTITY'], ['TIME.EVENT_TIME', 'EVENT'], ['ESCHATOLOGY.BARZAKH_EVENT', 'EVENT'], ['ESCHATOLOGY.HISAB_EVENT', 'EVENT'], ['ESCHATOLOGY.JANNAH_STATE', 'EVENT'], ['ESCHATOLOGY.JAHANNAM_STATE', 'EVENT'],
  ['FINANCE.ZAKAT_ASSESSMENT', 'EVENT'], ['FINANCE.TAX_ASSESSMENT', 'EVENT'], ['FINANCE.JIZYAH_ASSESSMENT', 'EVENT'], ['AUTH.ACCOUNT', 'ENTITY'], ['AUTH.SESSION', 'EVENT'], ['AUTH.FEATURE', 'ENTITY'], ['LIFECYCLE.MODE_PROFILE', 'ENTITY'], ['LIFECYCLE.PUBLICATION', 'EVENT'], ['LIFECYCLE.PUBLICATION_GATE', 'ENTITY'],
  ['IDENTITY.PERSON', 'ENTITY'], ['IDENTITY.ORGANIZATION', 'ENTITY'], ['IDENTITY.PLACE', 'ENTITY'], ['RELIGIOUS.MOSQUE', 'ENTITY'], ['RELIGIOUS.CHURCH', 'ENTITY'], ['EDUCATION.SCHOOL', 'ENTITY'], ['HEALTH.HOSPITAL', 'ENTITY'], ['GOVERNANCE.OFFICE', 'ENTITY'], ['FINANCE.BANK_ACCOUNT', 'RESOURCE'], ['FINANCE.ZAKAT', 'RESOURCE_FLOW'], ['FINANCE.TAX', 'RESOURCE_FLOW'], ['FINANCE.JIZYAH', 'RESOURCE_FLOW'], ['EMPLOYMENT.SALARY', 'RESOURCE_FLOW'], ['PROJECT.PUBLIC_PROJECT', 'EVENT'], ['JUSTICE.CASE', 'ENTITY'], ['JUSTICE.COURT_EVENT', 'EVENT'], ['MEDIA.CLAIM', 'EVENT'], ['CYBER.INCIDENT', 'EVENT'], ['AI.OUTPUT', 'EVENT'], ['AMAL.EVENT', 'EVENT'], ['ESCHATOLOGY.STATE_EVENT', 'EVENT'],
];

export const DOMAIN_TYPES: readonly DomainType[] = Object.freeze(rawTypes.map(([typeId, entityFamily]) => ({ typeId, entityFamily, domain: typeId.split('.')[0] })));

export interface TypeRuntime { types: { list(): DomainType[] }; registerType(type: DomainType): DomainType }

export function registerCoreDomainTypes(runtime: TypeRuntime): DomainType[] {
  const existing = new Set(runtime.types.list().map((type) => type.typeId));
  return DOMAIN_TYPES.filter((type) => !existing.has(type.typeId)).map((type) => runtime.registerType(type));
}
